server:
  port: 8081
  servlet:
    context-path: /api/spider
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://47.100.164.178:3306/spider?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: spider
    password: spider112
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.hwt.spider.entity.pojo
#sql打印在控制台
logging:
  level:
    root: info
    com.hwt.spider.mapper: debug