create table `SPIDER_MUSIC`(
	`ID` int(21) NOT NULL AUTO_INCREMENT,
	`MUSIC_NAME` VARCHAR(20) NOT NULL,
	`AUTHOR` VARCHAR(20),
	`URL` VARCHAR(255),
	`CREATE_TIME` datetime NOT NULL,
	PRIMARY KEY(`ID`)
)ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8

create table `SPIDER_FICTION`(
	`ID` int(21) NOT NULL AUTO_INCREMENT,
	`FICTION_NAME` VARCHAR(20) NOT NULL,
	`AUTHOR` VARCHAR(20),
	`URL` VARCHAR(255),
	`CREATE_TIME` datetime NOT NULL,
	PRIMARY KEY(`ID`)
)ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8